#!/usr/bin/env bash

set -euo pipefail

echo "Checking out branch" >&2
git checkout -B ${BUILDKITE_BRANCH}
git branch -u origin/${BUILDKITE_BRANCH}
git config branch.${BUILDKITE_BRANCH}.remote origin
git config branch.${BUILDKITE_BRANCH}.merge refs/heads/${BUILDKITE_BRANCH}
git clean -df

echo "Running SBT release..." >&2
sbt "release with-defaults skip-tests"